// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXcq1STIwpZnW-JIWSd9Y8Z6u1dGByxak',
    appId: '1:525642506735:android:da23bd296340e70c01d61a',
    messagingSenderId: '525642506735',
    projectId: 'asistencia-alumnos-2025',
    storageBucket: 'asistencia-alumnos-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEc57AgPoAHsEJ9B_yMVeSpPMv0hhVMqQ',
    appId: '1:525642506735:ios:407401ec5aea079b01d61a',
    messagingSenderId: '525642506735',
    projectId: 'asistencia-alumnos-2025',
    storageBucket: 'asistencia-alumnos-2025.firebasestorage.app',
    iosBundleId: 'com.example.asistenciasApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcq1STIwpZnW-JIWSd9Y8Z6u1dGByxak',
    appId: '1:525642506735:web:da23bd296340e70c01d61a',
    messagingSenderId: '525642506735',
    projectId: 'asistencia-alumnos-2025',
    storageBucket: 'asistencia-alumnos-2025.firebasestorage.app',
  );
}
